### ISSUE TITLE
dbg.logへのアクセスが失敗し起動失敗となります

### ISSUE THREAD

**Issue by sumesimof** [dj-kata/inf_daken_counter_obsw#14]
お世話になってますsuemsiです

実行確認ver 2.0.22
確認日　23/9/17

dbg.logへのアクセスが失敗し起動失敗となります
・PC再起動後に実施しています。
・日々のノーツ数の算出：しない、する　
どちらでも同じエラーが発生。

添付ファイルを参照ください。

[dakenlog230917.v2.0.22.txt](https://github.com/dj-kata/inf_daken_counter_obsw/files/12642173/dakenlog230917.v2.0.22.txt)

**Comment by dj-kata** [comment]
お世話になっております。
ご報告ありがとうございます。

この問題、恐らく打鍵カウンタを起動した時点で発生しますかね？
2.0.21の時に私の環境で一度発生した際は、dbg.logを一度削除することでそれ以降は問題なく起動するようになりました。もしそのような状況であれば試していただけたらと思います。

(これでも解決しない場合、インストール先の問題かもしれません)

**Comment by dj-kata** [comment]
あと、2.0.22で入れた対策がまだ不十分かもしれないので帰宅したらそこも調査します。

**Comment by sumesimof** [comment]
早速のご確認ありがとうございます🙏
帰宅したらdbg.logを消してやってみます。
インストール先は
d:￥tool￥inf_daken_counter￥
で、windows osが入ってないドライブです。

**Comment by dj-kata** [comment]
インストール先については問題なさそうですね。
(デスクトップとかだとOnedriveの影響で変なことになるようです)
closeされていますが、まだ解決しないようでしたらreopenしていただけたらと思います。

**Comment by dj-kata** [comment]
別モジュールからでも同一のルートロガーを参照しているつもりでしたが、同一ファイルへの書き込みだとやはりプロセス間の競合が起きてそうなので、少し対策を入れることにしました。
一旦チケットはOPENに戻します。

**Comment by sumesimof** [comment]
念のため、
dbg.logを該当フォルダから消して起動→Startすると正常に起動しました。

**Comment by dj-kata** [comment]
今上げた最新版(v.2.0.23)で対策しました。ご確認をお願いします。
https://github.com/dj-kata/inf_daken_counter_obsw/releases/tag/v.2.0.23
