### ISSUE TITLE
初回ダウンロード後、notes_counter.exeが起動しない。

### ISSUE THREAD

**Issue by yukisync** [dj-kata/inf_daken_counter_obsw#17]
v.2.0.29のダウンロード→インストール
および
v.2.0.28のダウンロード→インストールでnotes_counter.exeを実行しようとした際に
![image](https://github.com/dj-kata/inf_daken_counter_obsw/assets/51686613/a8cb3341-fa49-4013-a618-2a2231e2a184)
のようなログが出ます。
確かにみると、settings.jsonがないのですが、ない場合に起動時に作成されるとあります。

![image](https://github.com/dj-kata/inf_daken_counter_obsw/assets/51686613/e96a321f-4173-4adf-8abe-3608fce52050)

システムOSも64bitです。
![image](https://github.com/dj-kata/inf_daken_counter_obsw/assets/51686613/6b0b45fd-e759-4ece-9e43-e0bdcd44ca30)

この場合、直接settings.jsonファイルを作成すればいいですか？

**Comment by dj-kata** [comment]
ご報告ありがとうございます。
インストール先のフォルダに書き込めない問題に見えるのですが、デスクトップ以下に本アプリを解凍されていませんでしょうか？
例えばDドライブ直下などに移動すると解決するかもしれません。

**Comment by yukisync** [comment]
ご指摘の通り、デスクトップに解凍していたので、C直下で試したところ、settings.jsonが作成されました。
お早い回答、ありがとうございます。

**Comment by dj-kata** [comment]
解決したようで良かったです！
今後ともよろしくお願いします。
