### ISSUE TITLE
today_updateとHistory_cursongの情報が反映されない

### ISSUE THREAD

**Issue by chirashizushi321** [dj-kata/inf_daken_counter_obsw#21]
OBS上に配置しているtoday_update.htmlとHistory_cursong.htmlの情報が反映されなくなりました。
バージョン：2.0.43
3日前には問題なく動いていましたが、INFINITASが突然落ちてしまい、ゲーム再起動→OBS再起動→打鍵カウンター起動後から一切情報が更新されなくなりました。

その後、クライアントをDLして既存ファイルに上書き後はHistory_cursong.htmlの情報は表示されるも過去の更新情報しか表示されず、新規のリザルトは反映されていません。
ログファイルを添付いたします。
よろしくお願いいたします。

[update.log](https://github.com/user-attachments/files/16621450/update.log)
[daken_logger.log](https://github.com/user-attachments/files/16621451/daken_logger.log)
[detect_core.log](https://github.com/user-attachments/files/16621452/detect_core.log)
[manage_output.log](https://github.com/user-attachments/files/16621453/manage_output.log)
[notes_counter.log](https://github.com/user-attachments/files/16621454/notes_counter.log)
[obssocket.log](https://github.com/user-attachments/files/16621455/obssocket.log)

**Comment by dj-kata** [comment]
- 作者の環境: OBSver:30.2.0, RPCver:1, OBSWSver:5.5.1
- 今回の環境: OBSver:30.2.2, RPCver:1, OBSWSver:5.5.2

見たところ、3日前ぐらいから曲名認識がすべて失敗してそうな雰囲気ですね…。
バージョンを合わせた環境で再現しないか確認します。

あと、上げていただいたdetect_core.logだけアップロードに失敗してそう(変なxmlが出てきてしまう)のですが、  
こちらを再度上げていただけますでしょうか？

**Comment by dj-kata** [comment]
もう1点お願いしたいことが出てきたのでまとめます。

1. log/detect_core.logを再度送っていただきたいです
2. (打鍵カウンタを起動した状態で)リザルト画面でF6を押した時に保存された画像を1枚でもいいので送っていただきたいです

**Comment by chirashizushi321** [comment]
お世話になります。どうぞよろしくお願いいたします。

![infinitas_20240816_090922](https://github.com/user-attachments/assets/3e6c3bfa-71d8-4e05-82ec-05f738358a77)
[detect_core.log](https://github.com/user-attachments/files/16631393/detect_core.log)

**Comment by dj-kata** [comment]
ありがとうございます。
OBSのソースにも問題はなさそうです。

Twitterでのやりとりで気になったのですが、デスクトップ以下にインストールされているせいで認識用リソースファイルが変なことになっている可能性がありそうです。OneDriveが干渉してこないフォルダ(Dドライブ内など)に移してから確認してもらえますでしょうか？

**Comment by chirashizushi321** [comment]
お世話になります。DドライブがないのでC直下にフォルダを置いて動作確認をしましたが、現象変わらず…でした。
スコアの読み取り自体は問題ないのですが…

すみません、引き続きよろしくお願いいたします。

**Comment by dj-kata** [comment]
ご確認ありがとうございます。
直接の原因が見つかっておらず申し訳ない限りですが、曲名認識結果の一部が意図通りになっていない可能性があるかもしれない(&細かい情報までログファイルに出力していない)ため、次のアプデでダンプ機能を一部追加します。
アプデ後に再度ログを見させてください。

**Comment by dj-kata** [comment]
本問題ですが、こちらでも再現できたので直接調べます。

**Comment by dj-kata** [comment]
inf-notebook(リザルト手帳)で使っているresources内のファイルについて、最新版が同梱できていないものがあったのが原因でした。
対策したものを次回アプデで出します。

**Comment by dj-kata** [comment]
https://x.com/chirashi321/status/1825470122565472313
npyファイルの差し替えで動いたとのことなのでcloseします。
