### ISSUE TITLE
リポジトリの内容が配布されている最新リリースと一致していない

### ISSUE THREAD

**Issue by ryowatanabe** [dj-kata/inf_daken_counter_obsw#7]
先週くらいから打鍵カウンタを利用させていただいています。
手元の環境だと、履歴をファイルに書き出す際ときどきパーミッションエラーで落ちてしまう場合があることがわかりました。(多いと1時間に数回程度)

![error](https://github.com/dj-kata/inf_daken_counter_obsw/assets/1335397/1d98f229-7dda-4388-a9c7-f21100bdf570)

再現性が環境依存の可能性もあるため、自分の手元でデバッグ実行しつつ動作確認して、可能なら修正のpull requestをお送りしようかと考え、手元で開発・デバッグできる環境を整えてみましたが、リポジトリの内容が一部最新版と一致しなかったり、不足しているファイルがあるようです。

いまわかっている範囲だと以下がありました。

 - `gui/` ディレクトリ以下の内容が欠けている
 - `noteslist.pkl` の内容が最新でない

こちらお手数ですが、リポジトリの内容が最新リリースと一致するように更新していただいてもよいでしょうか。
よろしくお願いします。

**Comment by ryowatanabe** [comment]
なお、環境は以下のとおりです。

```
OS: Windows11 Home 64bit (22H2)
CPU: Core i7-11700
GPU: GeForce RTX 3060 Ti
ウイルス対策ソフト: Windows Defender
OBS: 29.1.2
```

**Comment by dj-kata** [comment]
ご報告ありがとうございます。  
[ef361ed](https://github.com/dj-kata/inf_daken_counter_obsw/commit/ef361eda6d783bc4c46fccf23f9962b1eca7cb87)にてコミット漏れに対応しました。

**Comment by dj-kata** [comment]
Permission deniedについて、インストール先フォルダが気になるのですが、
Appdata直下などになっていますでしょうか？
もしかしたら、ディスクドライブ直下(例:```D:\```等)にインストールすると改善する可能性があるかもしれません。

**Comment by ryowatanabe** [comment]
最新版を手元に持ってきてみたところ、期待通りの動作になっていそうです。
早速の対応ありがとうございます！

インストール先(配置場所)はデスクトップでした。
切り分けのためにドライブ直下も試してみたいと思いますが、エラーが発生するのが確率的であるため、単純なフォルダ権限の問題というよりは二重ファイルオープンなど排他制御周りかもしれないと考えており、それはそれでログを出しながら見ていきたいと思います。

**Comment by dj-kata** [comment]
こちらのissueについて、インストール先変更で改善したとのことだったので一旦closeします。何かありましたらreopenしてお知らせください。
